### ISSUE TITLE
Add support for custom logger

### ISSUE THREAD

**Issue by iMacTia** [grantila/trace-unhandled#2]
In a Back End service application, chances are that there's already an existing logger tight to the logging system (e.g. Logstash and Kibana) that one might want to use.
However, at the moment, `trace-unhandled` only allows to log using `console.error`.
It would make sense to keep that as the default behaviour, while providing the possibility to override that and use a custom logger.

What do you think?

**Comment by grantila** [comment]
That sounds very reasonable, I'll look into it.

**Comment by mattiagiuffrida-st** [comment]
Thanks @grantila for the quick fix 🎉 !
